#!/bin/sh


echo  ============ Final Time = 100 =====================


echo -------------- 1 worker --------------------------
time -p ./mainOMP 100 1

echo -------------- 2 workers --------------------------
time -p ./mainOMP 100 2


echo -------------- 4 workers --------------------------
time -p ./mainOMP 100 4

echo -------------- 8 workers --------------------------
time -p ./mainOMP 100 8

echo -------------- 16 workers --------------------------
time -p ./mainOMP 100 16

#echo -------------- 32 workers --------------------------
#./mainOMP 50 32




echo
echo
echo
echo ============ Final Time = 200 =====================


echo -------------- 1 worker --------------------------
time -p ./mainOMP 200 1

echo -------------- 2 workers --------------------------
time -p ./mainOMP 200 2


echo -------------- 4 workers --------------------------
time -p ./mainOMP 200 4

echo -------------- 8 workers --------------------------
time -p ./mainOMP 200 8


echo -------------- 16 workers --------------------------
time -p ./mainOMP 200 16

#echo -------------- 32 workers --------------------------
#./mainOMP 100 32


echo
echo
echo
echo  ============ Final Time = 400 =====================


echo -------------- 1 worker --------------------------
time -p ./mainOMP 400 1

echo -------------- 2 workers --------------------------
time -p ./mainOMP 400 2

echo -------------- 4 workers --------------------------
time -p ./mainOMP 400 4

echo -------------- 8 workers --------------------------
time -p ./mainOMP 400 8

echo -------------- 16 workers --------------------------
time -p ./mainOMP 400 16

#echo -------------- 32 workers --------------------------
#./mainOMP 200 32




echo
echo
echo
echo  ============ Final Time = 800 =====================


echo -------------- 1 worker --------------------------
time -p ./mainOMP 800 1

echo -------------- 2 workers --------------------------
time -p ./mainOMP 800 2

echo -------------- 4 workers --------------------------
time -p ./mainOMP 800 4

echo -------------- 8 workers --------------------------
time -p ./mainOMP 800 8

echo -------------- 16 workers --------------------------
time -p ./mainOMP 800 16

#echo -------------- 32 workers --------------------------
#./mainOMP 400 32




echo
echo
echo
echo  ============ Final Time = 1600 =====================


echo -------------- 1 worker --------------------------
time -p ./mainOMP 1600 1

echo -------------- 2 workers --------------------------
time -p ./mainOMP 1600 2


echo -------------- 4 workers --------------------------
time -p ./mainOMP 1600 4

echo -------------- 8 workers --------------------------
time -p ./mainOMP 1600 8


echo -------------- 16 workers --------------------------
time -p ./mainOMP 1600 16

